config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new()
  end

  def create
    article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit

  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_edit.html.erb
<%= form_for(article) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control', rows: '10' %>

  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'edit', article: @article %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div>
    <%= link_to article_path(article) do %>
      <h2><%= article.title %></h2>
    <% end %>
    <p><%= article.content[0, 30] %></p>
    <p>last updated: <%= article.updated_at %></p>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render 'edit', article: @article %>

app/views/articles/show.html.erb
<div class="border rounded">
  <div class="d-flex align-items-center">
    <h1><%= @article.title %></h1>
    <%= link_to article_path(@article), method: :delete do %>
      <i class="far fa-trash-alt ml-3"></i>
    <% end %>
    <%= link_to edit_article_path(@article) do %>
      <i class="fas fa-pencil-alt ml-3"></i>
    <% end %>
  </div>
  <p><%= @article.content %></p>
  <p><%= @article.updated_at %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <div class="navbar bg-light mb-3 border-bottom">
      <div class="container">
        <a class="navbar-brand" href="/">Home</a>
        <a href="articles/new" class="nav-item">New Article</a>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>